name: Build xLuaDumper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    name: Build with Visual Studio 2019
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '16.0' # Visual Studio 2019

    - name: Build with MSBuild
      run: msbuild xLuaDumper.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: xLuaDumper-build
        path: |
          **/Release/*.exe
          **/Release/*.dll
