name: Build xLuaDumper

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup MSBuild (Visual Studio 2019)
      uses: microsoft/setup-msbuild@v1.1
      with:
        vs-version: '16.0'

    - name: Build Solution
      run: msbuild xLuaDumper.sln /p:Configuration=Release

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: xLuaDumper-build
        path: |
          **/Release/*.exe
          **/Release/*.dll
